name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  sandboxes:  # id of input
    description: 'list:sandboxes json'
    required: true
    default: '[]'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
