name: 'Manage On-Demand Sandboxes'
description: 'Wait a designated number of milliseconds'
inputs:
  sandboxes:
    description: 'JSON with all active sandboxes'
    required: true
    default: '[]'
  event:
    description: 'SFCC CI Sandbox event'
    required: false
    default: 'stop'
outputs:
  message:
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
