name: 'SalesForce B2C On-Demand Sandboxes'
description: 'Manage On-Demand Sandboxes'
inputs:
  sandboxes:
    description: 'JSON with all active sandboxes'
    required: true
    default: '[]'
  event:
    description: 'SFCC CI Sandbox event'
    required: false
    default: 'stop'
runs:
  using: 'node12'
  main: 'dist/index.js'
